fieldLayouts:
  f529945f-85e4-4cf0-8155-4452804d2748:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fd7d1804-1707-460b-8e19-a89140b2a233
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aba2271c-70a4-48e6-a1aa-ac67c9bf1376 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0c22cf5-c9f4-4c69-b231-5ba937a5d08b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcbaea6d-9ec6-4ad1-9496-e6e832a02596 # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44055b4b-be4a-431c-99fc-c1d566505cc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64afc6de-478f-4834-badc-d14b9df2f466
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 896e2380-7081-4eec-8437-9f2aadc950ae # Article
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
