fieldLayouts:
  8d516119-fb4d-4dbe-b1e4-3ffb15f2972a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cb0b4b99-6ce9-458c-b9a1-8c1ebf80a690
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0908eec4-7665-4126-a890-e6cafddbbbd7
        userCondition: null
handle: newspapersHomepage
hasTitleField: false
name: 'Newspapers Homepage'
section: a6dd2ad7-850d-4664-8c39-5044dcb85e6f # Newspapers Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
