baseUrl: 'https://newspaper-multisite.ddev.site/yassvalleytimes/'
enabled: '1'
handle: yassValleyTimes
hasUrls: true
language: en-AU
name: 'Yass Valley Times'
primary: false
siteGroup: f51b3682-1768-4364-aecf-52c44251c479 # Newspaper Multisite
sortOrder: 4
