columnSuffix: null
contentColumnType: string
fieldGroup: 001630a1-7ce4-4a23-b580-7d9616154ff6 # Common
handle: categories
instructions: null
name: Categories
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:b74c8a5b-1469-4ee7-a88a-c95ef39a4266' # Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
